// <auto-generated />
namespace CTU_Training_Solutions_Capture_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class A : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A));
        
        string IMigrationMetadata.Id
        {
            get { return "202105181907519_A"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
